import type { Icon as IconsaxIcon } from "iconsax-react";
import {
	AddCircle,
	AddSquare,
	ArrowDown,
	ArrowDown2,
	ArrowLeft,
	ArrowLeft2,
	ArrowRight,
	ArrowRight2,
	ArrowUp,
	ArrowUp2,
	Calendar2,
	Danger,
	Edit2,
	Eye,
	EyeSlash,
	Facebook,
	Gallery,
	Google,
	Heart,
	Information,
	Key,
	Location,
	MedalStar,
	More,
	People,
	SearchNormal1,
	Setting4,
	Sms,
	Trash,
	User,
	Wallet,
} from "iconsax-react";

export const Icon = {
	ArrowUp,
	ArrowRight,
	ArrowDown,
	ArrowLeft,
	Calendar: Calendar2,
	ChevUp: ArrowUp2,
	ChevRight: ArrowRight2,
	ChevDown: ArrowDown2,
	ChevLeft: ArrowLeft2,
	Delete: Trash,
	Edit: Edit2,
	Email: Sms,
	Error: Danger,
	Ellipsis: More,
	Facebook,
	Filter: Setting4,
	Google,
	Heart,
	Key: Key,
	Hide: EyeSlash,
	Info: Information,
	Image: Gallery,
	Lomba: MedalStar,
	Location,
	Organizer: People,
	PlusCircle: AddCircle,
	PlusSquare: AddSquare,
	Reveal: Eye,
	Search: SearchNormal1,
	User,
	Wallet,
};

export type Icon = IconsaxIcon;
export type IconKeys = keyof typeof Icon;
